# Generated by Django 4.1 on 2022-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('profession', models.CharField(max_length=50)),
                ('complement', models.CharField(max_length=100)),
            ],
        ),
    ]
