# Generated by Django 4.1 on 2022-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
