# Generated by Django 4.1 on 2022-11-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0002_character_age_character_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('不明', '不明')], max_length=2),
        ),
    ]
