# Generated by Django 4.1 on 2022-11-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0003_alter_character_options_alter_character_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=100, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='complement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='chapter',
            field=models.ManyToManyField(to='conan_db_app.chapter'),
        ),
    ]
