# Generated by Django 4.1 on 2022-11-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0004_chapter_alter_character_complement_character_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
