# Generated by Django 4.1 on 2022-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0005_alter_chapter_complement_alter_character_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('cause_of_death', models.CharField(blank=True, max_length=100, null=True)),
                ('number_of_victim', models.IntegerField(blank=True, null=True)),
                ('number_of_perpetrator', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('motivation', models.CharField(blank=True, max_length=100, null=True)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='character',
            name='case_solved_by',
            field=models.ManyToManyField(to='conan_db_app.case'),
        ),
    ]
