# Generated by Django 4.1 on 2022-11-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0006_case_volume_character_case_solved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='volume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.volume'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.case'),
        ),
    ]
