# Generated by Django 4.1 on 2022-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0007_case_volume_chapter_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='case_solved_by',
            field=models.ManyToManyField(blank=True, to='conan_db_app.case'),
        ),
    ]
