# Generated by Django 4.1 on 2022-11-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0008_alter_character_case_solved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='id',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='id',
        ),
        migrations.AlterField(
            model_name='case',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volume',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
