# Generated by Django 4.1 on 2022-11-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0010_remove_case_volume_chapter_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
