# Generated by Django 4.1 on 2022-12-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0011_alter_case_complement_alter_chapter_complement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='case_solved_by',
            field=models.ManyToManyField(to='conan_db_app.case'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='event_related_to',
            field=models.ManyToManyField(to='conan_db_app.event'),
        ),
    ]
