# Generated by Django 4.1 on 2022-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0012_alter_character_case_solved_by_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='case_solved_by',
            field=models.ManyToManyField(null=True, to='conan_db_app.case'),
        ),
        migrations.AlterField(
            model_name='character',
            name='event_related_to',
            field=models.ManyToManyField(null=True, to='conan_db_app.event'),
        ),
    ]
