# Generated by Django 4.1 on 2022-12-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0013_alter_character_case_solved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='case_solved_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='event_related_to',
        ),
        migrations.AddField(
            model_name='character',
            name='case_solved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.case'),
        ),
        migrations.AddField(
            model_name='character',
            name='event_related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.event'),
        ),
    ]
