# Generated by Django 4.1 on 2022-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0014_remove_character_case_solved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='case_solved_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='event_related_to',
        ),
        migrations.AddField(
            model_name='character',
            name='case_solved_by',
            field=models.ManyToManyField(to='conan_db_app.case'),
        ),
        migrations.AddField(
            model_name='character',
            name='event_related_to',
            field=models.ManyToManyField(to='conan_db_app.event'),
        ),
    ]
