# Generated by Django 4.1 on 2022-12-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0015_remove_character_case_solved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('問題', 'question'), ('アンケート', 'questionnaire')], max_length=20)),
                ('content', models.TextField()),
                ('n_option', models.IntegerField(choices=[('2', 2), ('3', 3), ('4', 4), ('5', 5)])),
                ('option1', models.TextField()),
                ('option2', models.TextField()),
                ('option3', models.TextField(blank=True, null=True)),
                ('option4', models.TextField(blank=True, null=True)),
                ('option5', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
