# Generated by Django 4.1 on 2022-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0016_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('question', '問題'), ('questionnaire', 'アンケート')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='n_option',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
