# Generated by Django 4.1 on 2022-12-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0017_alter_question_kind_alter_question_n_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='jenre',
            field=models.CharField(choices=[('conan', '名探偵コナン関係'), ('others', 'それ以外')], default='others', max_length=20),
            preserve_default=False,
        ),
    ]
