# Generated by Django 4.1 on 2022-12-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0018_question_jenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='jenre',
            field=models.CharField(choices=[('conan', '名探偵コナン関係'), ('others', 'それ以外')], default='conan', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('question', '問題'), ('questionnaire', 'アンケート')], default='question', max_length=20),
        ),
    ]
