# Generated by Django 4.1 on 2023-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0019_alter_question_jenre_alter_question_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='cause_of_death',
        ),
        migrations.RemoveField(
            model_name='case',
            name='motivation',
        ),
        migrations.RemoveField(
            model_name='case',
            name='number_of_perpetrator',
        ),
        migrations.RemoveField(
            model_name='case',
            name='number_of_victim',
        ),
        migrations.RemoveField(
            model_name='case',
            name='relationship',
        ),
        migrations.RemoveField(
            model_name='case',
            name='type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='character',
            name='case_solved_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.AddField(
            model_name='case',
            name='kind',
            field=models.IntegerField(choices=[('black', '黒の組織'), ('love', '恋愛'), ('police', '警察関係'), ('kid', 'キッド'), ('fbi', 'FBI'), ('red', '赤井家')], null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='skill',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='complement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='complement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='complement',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='profession',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='complement',
            field=models.TextField(null=True),
        ),
    ]
