# Generated by Django 4.1 on 2023-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0021_character_belong_to_alter_case_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='kind',
            field=models.CharField(choices=[('黒の組織', '黒の組織'), ('恋愛', '恋愛'), ('警察関係', '警察関係'), ('KID', 'KID'), ('FBI', 'FBI'), ('赤井家', '赤井家')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='belong_to',
            field=models.CharField(choices=[('帝丹小学校', '帝丹小学校'), ('帝丹高校', '帝丹高校'), ('東都大学', '東都大学'), ('黒の組織', '黒の組織'), ('毛利家', '毛利家'), ('警察', '警察'), ('FBI', 'fbi'), ('SIS', 'SIS'), ('NOC', 'NOC'), ('赤井家', '赤井家')], max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='profession',
            field=models.CharField(choices=[('小学生', '小学生'), ('高校生', '高校生'), ('警察官', '警察官'), ('探偵', '探偵'), ('FBI捜査官', 'FBI捜査官')], max_length=30, null=True),
        ),
    ]
