# Generated by Django 4.1 on 2023-01-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0022_alter_case_kind_alter_character_belong_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='belong_to',
            field=models.CharField(choices=[('帝丹小学校', '帝丹小学校'), ('帝丹高校', '帝丹高校'), ('東都大学', '東都大学'), ('黒の組織', '黒の組織'), ('毛利家', '毛利家'), ('警察', '警察'), ('FBI', 'FBI'), ('SIS', 'SIS'), ('NOC', 'NOC'), ('赤井家', '赤井家')], max_length=30),
        ),
    ]
