# Generated by Django 4.1 on 2023-01-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0023_alter_character_belong_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='kind',
            field=models.CharField(blank=True, choices=[('黒の組織', '黒の組織'), ('恋愛', '恋愛'), ('警察関係', '警察関係'), ('KID', 'KID'), ('FBI', 'FBI'), ('赤井家', '赤井家')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volume',
            name='complement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
