# Generated by Django 4.1 on 2023-01-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0025_alter_character_event_related_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='event_related_to',
            field=models.ManyToManyField(blank=True, to='conan_db_app.event'),
        ),
    ]
