# Generated by Django 4.1 on 2023-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0026_alter_character_event_related_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='belong_to',
        ),
        migrations.RemoveField(
            model_name='character',
            name='profession',
        ),
        migrations.AddField(
            model_name='character',
            name='belong_to',
            field=models.ManyToManyField(to='conan_db_app.affiliation'),
        ),
        migrations.AddField(
            model_name='character',
            name='profession',
            field=models.ManyToManyField(blank=True, to='conan_db_app.profession'),
        ),
    ]
