# Generated by Django 4.1 on 2023-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0027_affiliation_profession_remove_character_belong_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='aaa', max_length=30),
            preserve_default=False,
        ),
    ]
