# Generated by Django 4.1 on 2023-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0028_case_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number_in_all',)},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='number',
            new_name='number_in_all',
        ),
        migrations.AddField(
            model_name='chapter',
            name='number_in_volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
