# Generated by Django 4.1 on 2023-01-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0029_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='case',
            name='kind',
        ),
        migrations.AddField(
            model_name='case',
            name='kind',
            field=models.ManyToManyField(blank=True, to='conan_db_app.casekind'),
        ),
    ]
