# Generated by Django 4.1 on 2023-01-22 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0030_casekind_remove_case_kind_case_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='affiliation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.affiliation'),
            preserve_default=False,
        ),
    ]
