# Generated by Django 4.1 on 2023-02-02 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conan_db_app', '0032_alter_profession_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiseword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.chapter')),
                ('character', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='conan_db_app.character')),
            ],
        ),
    ]
